from fastapi import FastAPI
from datetime import datetime
from pathlib import Path

app = FastAPI()

SHARED_VIDEOS = Path("/shared/videos")

@app.get("/")
def root():
    return {"ok": True, "service": "python", "hint": "Try /health or /docs"}

@app.get("/health")
def health():
    return {"ok": True, "service": "python"}

@app.get("/compute")
def compute(x: int = 2, y: int = 3):
    return {"x": x, "y": y, "sum": x + y}

@app.post("/generate")
def generate():
    SHARED_VIDEOS.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.utcnow().isoformat()
    output_file = SHARED_VIDEOS / "test_output.txt"

    output_file.write_text(
        f"Generated by Python at {timestamp}\n",
        encoding="utf-8"
    )

    return {
        "ok": True,
        "written_to": str(output_file),
        "timestamp": timestamp
    }
